### PR TITLE
Correct terminal window mislabeling

### PR DESCRIPTION
**Pull request by kiyoto**
Noticed this while going through it. Pretty exciting stuff!

### CODE REVIEW

**Comment by kflynn** [comment]
Thanks for the catch! Can you take a look at https://github.com/datawire/datawire-connect/pull/9 and let me know if it makes things more clear?

**Comment by kiyoto** [comment]
Thanks! But I believe you still need to change the line with `fg` command in the same window as the one you paused a rating service (Window 2)?

**Comment by kflynn** [comment]
I think I've fixed it now, in pull 9 -- nice catch!

**Comment by kflynn** [comment]
Fixed in #9. :)

**Pull request closed without merging**
